### ISSUE TITLE
iOS 9 Support ?

### ISSUE THREAD

**Issue by Jinxiansen** [mh7821/SwiftBinanceChain#1]
Hi ! 
I saw in `README.md` that it supports **iOS 11+**, but can't it really support **iOS 9** ?
Or is there a way to support iOS 9 ? 🤔

**Comment by mh7821** [comment]
Hi Jinxiansen,

That was determined by the dependency [HDWalletKit](https://github.com/essentiaone/HDWallet), which has a minimum deployment target of iOS 11. You can build for iOS 9 by overriding that – let me know if you would like instructions.

**Comment by Jinxiansen** [comment]
https://github.com/essentiaone/HDWallet/issues/39
Here's why. 😅
